### ISSUE TITLE
Adding empty lore using ItemCreator throws an error.

### ISSUE THREAD

**Issue by hapyl** [hapyl/MMUReloaded#26]
java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
        at java.util.ArrayList.set(ArrayList.java:441) ~[?:?]
        at me.hapyl.mmu3.feature.itemcreator.gui.LoreSubGUI$1.onResponse(LoreSubGUI.java:55) ~[MapmakerUtilitiesReloaded.jar:?]
        at me.hapyl.spigotutils.module.reflect.protocol.SignListener.onPacketReceiving(SignListener.java:29) ~[EternaAPI.jar:?]
        at me.hapyl.spigotutils.module.reflect.protocol.ProtocolListener$1.onPacketReceiving(ProtocolListener.java:20) ~[EternaAPI.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:122) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:75) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:555) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketReceiving(PacketFilterManager.java:519) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketReceiving(NetworkManagerInjector.java:119) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processInboundPacket(NettyChannelInjector.java:488) ~[ProtocolLib.jar:?]

**Comment by hapyl** [comment]
No?
